#!/bin/python3

import sys


def print_ports(s):
    ports = s.split(",")
    for port in ports:
        print(f"interface range HundredGigE 1/0/{port}")
        print("using twenty-fivegige")


if __name__ == "__main__":
    print(sys.argv)

    if len(sys.argv) != 2:
        print("Use filename + ports numbers separated by ','")
        print("./cbis_ports.py 1,2,3")
    else:
        print_ports(sys.argv[1])
